FROM amazonlinux
RUN yum install -y unzip
RUN curl -o daemon.zip https://s3.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-linux-3.x.zip
RUN unzip daemon.zip && cp xray /usr/bin/xray
ENTRYPOINT ["/usr/bin/xray", "-t", "0.0.0.0:2000", "-b", "0.0.0.0:2000"]
EXPOSE 2000/udp
EXPOSE 2000/tcp

# NOTE: Always build it based on your expected platform or you will get below error. pc error: code = NotFound desc = failed to pull and unpack image "829007908826.dkr.ecr.ap-south-1.amazonaws.com/eks/custom-aws-xray-daemon:1.0.0": no match for platform in manifest: not found